name: Deploy

on:
  push:
    branches: [ main ]

jobs:
  Deploy:
    name: Deploy to EC2
    runs-on: ubuntu-latest

    steps:
    
      - uses: actions/checkout@v2 
      - name: Build & Deploy
        env:
            PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
            HOSTNAME: ${{secrets.EC2_HOST}}
            USER_NAME: ${{secrets.EC2_USERNAME}}

        run: |
          echo "Updating AWS widget:"
          echo "$PRIVATE_KEY" > private_key && chmod 600 private_key
          ssh -o StrictHostKeyChecking=no -i private_key ec2-user@16.170.255.102 '
              cd gwp_appendix_tsx/ &&
              git pull origin main &&
              cp -r AttachmentSelector/  /home/ec2-user/experience_builder/esri_projects/client/your-extensions/widgets/
              '
